//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by AsyncGenerator.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


using NHibernate.Multi;
using NUnit.Framework;

namespace NHibernate.Test.NHSpecificTest.NH2201
{
	using System.Threading.Tasks;
	using System.Threading;
	[TestFixture]
	public class FixtureAsync : BugTestCase
	{
		protected override bool AppliesTo(Engine.ISessionFactoryImplementor factory)
		{
			return factory.ConnectionProvider.Driver.SupportsMultipleQueries;
		}

		protected override void OnTearDown()
		{
			using (var s = OpenSession())
			using (var tx = s.BeginTransaction())
			{
				s.Delete("from System.Object");
				tx.Commit();
			}
		}

		protected override void OnSetUp()
		{
			using (var s = OpenSession())
			using (var tx = s.BeginTransaction())
			{
				s.Save(new Parent());
				s.Save(new SubClass() { Name = "test" });

				tx.Commit();
			}
		}

		[Test]
		public async Task CanUseQueryBatchAndFetchSelectAsync()
		{
			using (var s = OpenSession())
			{
				var multi =
					s.CreateQueryBatch()
					 .Add<Parent>(s.CreateCriteria<Parent>())
					 .Add<Parent>(s.CreateCriteria<Parent>());

				var result1 = await (multi.GetResultAsync<Parent>(0, CancellationToken.None));
				var result2 = await (multi.GetResultAsync<Parent>(1, CancellationToken.None));

				Assert.That(result1.Count, Is.EqualTo(2));
				Assert.That(result2.Count, Is.EqualTo(2));
			}
		}
	}
}
