//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by AsyncGenerator.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


using System;
using System.Data.Common;
using NHibernate.Engine;
using NHibernate.SqlTypes;
using NHibernate.Type;

namespace NHibernate.DomainModel.NHSpecific
{
	using System.Threading.Tasks;
	using System.Threading;
	public abstract partial class NullableTypesType : ImmutableType
	{

		public override async Task<object> NullSafeGetAsync(DbDataReader rs, string name, ISessionImplementor session, CancellationToken cancellationToken)
		{
			object value = await (base.NullSafeGetAsync(rs, name, session, cancellationToken));
			if (value == null)
			{
				return NullValue;
			}
			else
			{
				return value;
			}
		}
	}
}