using System.Data;
using System.Data.Common;
using NHibernate.Driver;
using NHibernate.SqlCommand;
using NHibernate.SqlTypes;

namespace NHibernate.Test.NHSpecificTest.GH1223
{
	// Wraps every DbCommand generated by the real Npgsql driver so a test can observe, without any
	// threading or timing, whether ISession.CancelQuery() actually reaches the command that is
	// currently executing.
	public class CancelSpyDriver : NpgsqlDriver
	{
		public static ISession Session;
		public static bool CancelCalled;

		public static void Reset()
		{
			Session = null;
			CancelCalled = false;
		}

		public override DbCommand GenerateCommand(CommandType type, SqlString sqlString, SqlType[] parameterTypes)
		{
			return new SpyCommand(base.GenerateCommand(type, sqlString, parameterTypes));
		}

		private class SpyCommand : DbCommand
		{
			private readonly DbCommand _command;

			public SpyCommand(DbCommand command)
			{
				_command = command;
			}

			public override int ExecuteNonQuery()
			{
				// Calls CancelQuery() from inside the command's own execution, which is equivalent to
				// (but deterministic, unlike) another thread calling ISession.CancelQuery() while this
				// command is running.
				Session?.CancelQuery();
				return _command.ExecuteNonQuery();
			}

			public override void Cancel()
			{
				CancelCalled = true;
				_command.Cancel();
			}

			public override void Prepare() => _command.Prepare();

			public override object ExecuteScalar() => _command.ExecuteScalar();

			protected override DbDataReader ExecuteDbDataReader(CommandBehavior behavior) => _command.ExecuteReader(behavior);

			protected override DbParameter CreateDbParameter() => _command.CreateParameter();

			protected override void Dispose(bool disposing)
			{
				base.Dispose(disposing);
				if (disposing)
				{
					_command.Dispose();
				}
			}

			public override string CommandText
			{
				get => _command.CommandText;
				set => _command.CommandText = value;
			}

			public override int CommandTimeout
			{
				get => _command.CommandTimeout;
				set => _command.CommandTimeout = value;
			}

			public override CommandType CommandType
			{
				get => _command.CommandType;
				set => _command.CommandType = value;
			}

			public override UpdateRowSource UpdatedRowSource
			{
				get => _command.UpdatedRowSource;
				set => _command.UpdatedRowSource = value;
			}

			protected override DbConnection DbConnection
			{
				get => _command.Connection;
				set => _command.Connection = value;
			}

			protected override DbParameterCollection DbParameterCollection => _command.Parameters;

			protected override DbTransaction DbTransaction
			{
				get => _command.Transaction;
				set => _command.Transaction = value;
			}

			public override bool DesignTimeVisible
			{
				get => _command.DesignTimeVisible;
				set => _command.DesignTimeVisible = value;
			}
		}
	}
}
