name: Generate Async code

on: 
  pull_request:
    paths:
      - '**.cs'

permissions: 
  contents: write

jobs:
  generate-async:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
      with:
        ref: ${{ github.event.pull_request.head.sha }}
        
        

    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 8.0.x

    - name: Generate Async code
      run: |
        pushd src
        dotnet tool restore
        dotnet restore ./NHibernate.sln
        dotnet async-generator
        popd

    - name: Push changes
      run: |
        git config user.name github-actions[bot]
        git config user.email github-actions[bot]@users.noreply.github.com
        if [[ -z "$(git status --porcelain)" ]]; then
            echo "No changes to commit"
            exit 0
        fi
        git add -A
        git commit -am "Generate async files"
        git remote set-url origin https://x-access-token:${{ secrets.GITHUB_TOKEN }}@github.com/$GITHUB_REPOSITORY
        git push
